#############################
### ENVIRONMENT VARIABLES ###
#############################

# Setting environment variables specifically relevant to Hyprland

# ssh-agent socket for systemd user unit
env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/ssh-agent.socket

# Explicitly setting XDG variables
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_CURRENT_DESKTOP,Hyprland

# UI toolkit backends and theming (prefer Wayland, scaling, and theming)
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORMTHEME,gtk3
env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,24
