###################
### LAYER RULES ###
###################

# Defining layers' behavior (use "hyprctl layers" to find layers' attributes)

# Fix random border appearing in screenshots
layerrule {
  name = fix-screenshot-border-appearing

  match:namespace = selection

  no_anim = on
}

# Dim everything around layers
layerrule {
    name = dim-around-layers

    match:namespace = (rofi|swaync-control-center)

    dim_around = on
}

####################
### WINDOW RULES ###
####################

# Defining windows' behavior (use "hyprctl clients" to find windows' attributes)

# Ignore maximize requests from all windows
windowrule {
    name = suppress-maximize-events

    match:class = .*

    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags

    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Float specific windows
windowrule {
    name = float-specific-windows

    match:class = (^hyprland-.*$|xdg-desktop-portal-gtk|udiskie|org.bleachbit.BleachBit|org.gnome.Characters)

    float = on
}
