##############
### LAYOUT ###
##############

# Defining the tiling layout Hyprland uses and how it behaves (e.g. master, scrolling, etc.)

# The layout currently in use and other general behavior settings
general {
    layout = master
    resize_on_border = true
}

# Master layout options
master {
    new_status = slave
    mfact = 0.5
}

###############
### VISUALS ###
###############

# Everything to do with the looks of Hyprland (borders, rounding, gaps, shadows, blur, animations, etc.)

# Sourcing the external color theme file
source = ~/.config/hypr/theme.conf

# Setting gaps, borders, and other general settings
general {
    gaps_in = 5
    gaps_out = 10

    border_size = 2

    col.active_border = $borderActiveColor
    col.inactive_border = $borderInactiveColor
}

# Border rounding, shadows, and blur
decoration {
    rounding = 10
    rounding_power = 10

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 10
        render_power = 10
        color = $shadowColor
    }

    blur {
        enabled = false
    }
}

# Desktop animations
animations {
   enabled = true

   # Bezier curves
   bezier = wind, 0.05, 0.9, 0.1, 1.05
   bezier = windIn, 0.1, 1.1, 0.1, 1.1
   bezier = smoothIn, 0.25, 1, 0.5, 1
   bezier = smoothOut, 0.36, 0, 0.66, -0.56
   bezier = overshot, 0.05, 0.9, 0.1, 1.055

   # Fade
   animation = fade, 1, 4, smoothIn
   animation = fadeIn, 1, 4, smoothIn
   animation = fadeOut, 1, 4, smoothOut
   animation = fadeSwitch, 1, 4, smoothIn
   animation = fadeShadow, 1, 4, smoothIn
   animation = fadeDim, 1, 4, smoothIn
   animation = fadeDpms, 1, 4, smoothIn

   # Workspaces
   animation = workspaces, 1, 4, overshot, slide
   animation = specialWorkspace, 1, 4, overshot, slidevert

   # Layers
   animation = layersIn, 1, 4, overshot, slide
   animation = layersOut, 1, 4, smoothOut, slide

   # Windows
   animation = windows, 1, 4, wind, slide
   animation = windowsIn, 1, 4, windIn, slide
   animation = windowsOut, 1, 4, smoothOut, slide
   animation = windowsMove, 1, 4, wind, slide
}
