#####################
### MISCELLANEOUS ###
#####################

# Defining miscellaneous configuration options

# Disabling splash message and other general settings
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    font_family = $fontFamily
    splash_font_family = $fontFamily
}
