################
### MONITORS ###
################

# Defining connected monitors and their options

# Main monitor settings (name is "description" from "hyprctl monitors" command)
$mainMonitor = desc:Chimei Innolux Corporation 0x1618
$mainMonitorResX = 1920
$mainMonitorResY = 1200
$mainMonitorRefresh = 60
$mainMonitorScale = 1.25
$mainMonitorPosition = 0x0

# Second monitor settings (name is "description" from "hyprctl monitors" command)
$secondMonitor = desc:BNQ BenQ GW2780 ETJCM0042204U
$secondMonitorResX = 1920
$secondMonitorResY = 1080
$secondMonitorRefresh = 60
$secondMonitorScale = 1
$secondMonitorPosition = {{$secondMonitorResX / $mainMonitorScale}}x0

# Main monitor rule
monitorv2 {
    output = $mainMonitor
    mode = $mainMonitorResXx$mainMonitorResY@$mainMonitorRefresh
    scale = $mainMonitorScale
    position = $mainMonitorPosition
}

# Second monitor rule
monitorv2 {
    output = $secondMonitor
    mode = $secondMonitorResXx$secondMonitorResY@$secondMonitorRefresh
    scale = $secondMonitorScale
    position = $secondMonitorPosition
}

# Fallback rule to mirror the main monitor by default
monitorv2 {
    output = 
    mode = $mainMonitorResXx$mainMonitorResY@$mainMonitorRefresh
    scale = auto
    position = auto
    mirror = $mainMonitor
}

# Use a scale of 1 for XWayland windows on scaled monitors to prevent pixelated or blurry look
xwayland {
    force_zero_scaling = true
}

##################
### WORKSPACES ###
##################

# Defining workspace-to-monitor behavior

# Workspaces on main monitor
workspace = 1, monitor:$mainMonitor, persistent:true, default:true
workspace = 2, monitor:$mainMonitor, persistent:true
workspace = 3, monitor:$mainMonitor, persistent:true
workspace = 4, monitor:$mainMonitor, persistent:true
workspace = 5, monitor:$mainMonitor, persistent:true

# Workspaces on second monitor
workspace = 6, monitor:$secondMonitor, persistent:true, default:true
workspace = 7, monitor:$secondMonitor, persistent:true
workspace = 8, monitor:$secondMonitor, persistent:true
workspace = 9, monitor:$secondMonitor, persistent:true
workspace = 10, monitor:$secondMonitor, persistent:true

# Special workspace behavior
workspace = special:SpecialWorkspace, persistent:true
