###################
### PERMISSIONS ###
###################

# Utilizing the Hyprland permission system to restrict programs' system access

# Enforce Hyprland compositor permissions (requires Hyprland restart to apply, format: path/regex, permission, mode)
ecosystem {
  enforce_permissions = true
}

# "screencopy" permission (access to screen without going through xdg-desktop-portal-hyprland)
permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(bin|local/bin)/hyprpicker, screencopy, allow
permission = /usr/(bin|local/bin)/hyprlock, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = .*, screencopy, deny

# "plugin" permission (access to load a plugin)
permission = .*, plugin, deny

# "keyboard" permission (access to connecting a new keyboard)
permission = .*, keyboard, allow
