################
### PROGRAMS ###
################

# Linking commonly used programs, scripts, and options to variables

# Essential services and system UI elements
$idleDaemon = hypridle
$udisks2Front = udiskie
$polkitAuthAgent = /usr/libexec/polkit-gnome-authentication-agent-1 || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
$wallpaperDaemon = awww-daemon
$statusBar = waybar
$notificationDaemon = swaync

# Native apps
$notificationMenu = swaync-client
$notificationMenuShowOpts = -t
$notificationMenuDndOpts = -d
$audioCtrl = pavucontrol
$audioCtrlCli = wpctl
$audioCtrlCliMuteOutputOpts = set-mute @DEFAULT_AUDIO_SINK@ toggle
$audioCtrlCliLowerOutputOpts = set-volume @DEFAULT_AUDIO_SINK@ 5%-
$audioCtrlCliRaiseOutputOpts = set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
$audioCtrlCliMuteInputOpts = set-mute @DEFAULT_AUDIO_SOURCE@ toggle
$audioCtrlCliLowerInputOpts = set-volume @DEFAULT_AUDIO_SOURCE@ 5%-
$audioCtrlCliRaiseInputOpts = set-volume -l 1 @DEFAULT_AUDIO_SOURCE@ 5%+
$nightLight = hyprsunset
$nightLightOpts = -t 3000 & sleep 0.25 && pkill -RTMIN+1 $statusBar
$screenshotApp = hyprshot
$screenshotAppRegionOpts = -s -z -m region
$screenshotAppWindowOpts = -s -z -m window
$screenshotAppMonitorOpts = -s -z -m output
$screenshotAppSaveOpts = -o $HOME/Pictures -f Screenshot_$(date +%Y-%m-%d_%H-%M-%S).png
$virtManager = virt-manager
$terminal = kitty
$secondaryTerminal = foot
$fileManager = nautilus
$vscode = code

# Flatpak apps
$bleachbit = flatpak run org.bleachbit.BleachBit
$emojiPicker = flatpak run org.gnome.Characters
$notepad = flatpak run org.gnome.TextEditor
$localSend = flatpak run org.localsend.localsend_app
$keePassXC = flatpak run org.keepassxc.KeePassXC
$yubicoAuthenticator = flatpak run com.yubico.yubioath
$brave = flatpak run com.brave.Browser
$bravePrivate = flatpak run com.brave.Browser --incognito
$firefox = flatpak run org.mozilla.firefox
$firefoxPrivate = flatpak run org.mozilla.firefox --private-window

# Scripts
$appLauncher = ~/.config/rofi/scripts/app-launcher.sh
$powerMenu = ~/.config/rofi/scripts/power-menu.sh
$backupScript = $secondaryTerminal -H bash -i -c bkup
$updateScript = $secondaryTerminal -H bash -i -c up

#################
### AUTOSTART ###
#################

# Auto-starting specific programs on Hyprland startup

# Essential services and system UI elements
exec-once = $idleDaemon
exec-once = $udisks2Front
exec-once = $polkitAuthAgent
exec-once = $wallpaperDaemon
exec-once = $statusBar
exec-once = $notificationDaemon
