source = ~/.config/hypr/theme.conf

# General
general {
    hide_cursor = true
    ignore_empty_input = true
}

# Background
background {
    monitor =
    path = 
    color = $mainBackground
}

# Date
label {
    monitor =
    color = $fontColor
    font_size = 20
    font_family = $fontFamilyBold
    halign = center
    valign = top
    position = 0, -150
    text = cmd[update:3600000] date +"%A, %d %B"
}

# Time
label {
    monitor =
    color = $fontColor
    font_size = 200
    font_family = $fontFamilyBold
    halign = center
    valign = center
    position = 0, 0
    text = $TIME12
}

# Password field
input-field {
    monitor =
    font_color = $fontColor
    inner_color = $mainBackground
    outer_color = $accentColor
    capslock_color = $warningColor
    fail_color = $failColor
    check_color = $accentColor
    font_family = $fontFamilyBold
    size = 340, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    hide_input = false
    fade_on_empty = false
    halign = center
    valign = bottom
    position = 0, 150
    placeholder_text = 󰍁 Enter Password
    fail_text = 󱗑 Authentication Failed
}

# Keyboard layout
label {
    monitor =
    color = $fontColor
    font_size = 15
    font_family = $fontFamilyBold
    halign = center
    valign = bottom
    position = 0, 100
    text =   $LAYOUT[en,ar]
}
