###################
### PERMISSIONS ###
###################

source = ~/.config/hypr/modules/permissions.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

source = ~/.config/hypr/modules/environment-variables.conf

############################
### PROGRAMS & AUTOSTART ###
############################

source = ~/.config/hypr/modules/programs-and-autostart.conf

#############################
### MONITORS & WORKSPACES ###
#############################

source = ~/.config/hypr/modules/monitors-and-workspaces.conf

############################
### LAYER & WINDOW RULES ###
############################

source = ~/.config/hypr/modules/layer-and-window-rules.conf

###########################
### INPUT & KEYBINDINGS ###
###########################

source = ~/.config/hypr/modules/input-and-keybindings.conf

########################
### LAYOUT & VISUALS ###
########################

source = ~/.config/hypr/modules/layout-and-visuals.conf

#####################
### MISCELLANEOUS ###
#####################

source = ~/.config/hypr/modules/miscellaneous.conf
