# Avoid starting multiple Hyprlock instances, lock before suspend, and avoid two key presses to enable display
general {
    lock_cmd = playerctl pause && pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# After 2.5 minutes, set monitor backlight to minimum and restore the backlight on resume
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# After 5 minutes, lock the screen
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# After 15 minutes, suspend the device
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
